export const OPEN_MODAL = 'OPEN_MODAL';
export const OPEN_MODAL_HISTORY = 'OPEN_MODAL_HISTORY';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const POST_ACTIVITY = 'POST_ACTIVITY';
export const FETCH_HISTORY_ITEM = 'FETCH_HISTORY_ITEM';

// --------------------------------------------------------
// Wired up to the backend
export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const FETCH_ACTIVITY_TYPES_REQUEST = 'FETCH_ACTIVITY_TYPES_REQUEST';
export const FETCH_ACTIVITY_TYPES_SUCCESS = 'FETCH_ACTIVITY_TYPES_SUCCESS';
export const FETCH_DOGS_REQUEST = 'FETCH_DOGS_REQUEST';
export const FETCH_DOGS_SUCCESS = 'FETCH_DOGS_SUCCESS';
export const FETCH_HISTORY_REQUEST = 'FETCH_HISTORY_REQUEST';
export const FETCH_HISTORY_SUCCESS = 'FETCH_HISTORY_SUCCESS';
